

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/entretainment-api
      username: root
      password: root
      uuid-representation: standard
entretainmentapi:
  jwt:
    secret: 5468566D597133743677397A24432646294A404E635266556A586E5A72347537
    expiration: 30000
logging:
  level:
    org:
      springframework:
        web: DEBUG
    root: debug
